name: Continuous Integration

 on:
   push:
     branches: ["Donal"]
 jobs:
    build: 
        runs-on: ubuntu-latest
        strategy:
            matrix: 
                node-version: [20.x]
        steps:
        - uses: actions/checkout@v4
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
                node-version: ${{ matrix.node-version }}
                cache: 'npm'                # to speed up the installation process    
        - run: npm ci        # A key command to ensure consistent and reliable builds in CI/CD by relying on strictly defined package versions, thereby improving the quality and predictability of deployments.
        - run: npm run build --if-present
        - run: npm test   # if we have a file test in the code